### ISSUE TITLE
Some improvement for launching screen

### ISSUE THREAD

**Issue by tvnmguy** [VueTubeApp/VueTube#585]
### Describe your suggested feature

1: VueTube logo with selected accent colour

2: New long thin loading bar placed to very bottom of the screen

### Other details

![IMG_20221129_092639](https://user-images.githubusercontent.com/116799295/204436186-1d094ab0-4b79-4f96-a05f-ad29b465e27a.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by PickleNik** [comment]
Implemented as an option
<img align=left width=300 src="https://user-images.githubusercontent.com/31113245/209583905-998956e9-078d-4f3f-9029-dabd12182248.png" />
<img align=right width=300 src="https://user-images.githubusercontent.com/31113245/209583914-29016589-3f29-4c98-986c-f33b509a2299.png" />

**Comment by tvnmguy** [comment]
@PickleNik 

Thanks😊

**Comment by PickleNik** [comment]
The toggle styling has since been improved btw 😎
![image](https://user-images.githubusercontent.com/31113245/209607516-0c363837-a31e-4f7a-9e4e-f30c4c9827c7.png)
![image](https://user-images.githubusercontent.com/31113245/209607531-8f2795f7-2a85-4fe9-8cf5-4225ff90d22f.png)
![image](https://user-images.githubusercontent.com/31113245/209607544-3173ecd9-fc84-4869-bb58-19e193d0e851.png)
![image](https://user-images.githubusercontent.com/31113245/209607553-f672bd31-3677-49be-8c3f-9d395d9a30ca.png)
![image](https://user-images.githubusercontent.com/31113245/209607562-17117eb5-66b2-4f8c-8920-0bf3c2c16165.png)
![image](https://user-images.githubusercontent.com/31113245/209607576-3c360e1a-e47f-4c14-9510-02e9a35a78c3.png)
