### ISSUE TITLE
[Android] Tap to seek

### ISSUE THREAD

**Issue by Eiskrem** [VueTubeApp/VueTube#67]
Please add 'Tap to seek' to to your upcoming app. I hate being forced to slide within progressbar. It's driving me nuts.

**Comment by Frontesque** [comment]
Tap to seek is just double tap on a side and it goes, right?

**Comment by Harmonie666** [comment]
> Tap to seek is just double tap on a side and it goes, right?

Single tap anywhere on the progressbar. This was the default behavior in stock YT for Android, until stupid Google decided to make it consistent with the iOS YT app. Vanced brought this feature back as a toggle because several users asked for it.

It's not like Android users are the majority and iOS should be consistent with Android if anything at all...

There are tons of posts in the Google support forum about users being extremely upset that this important feature got downgraded into a "tap, slide to desired time" thing.

Just to name a few: 

https://www.reddit.com/r/Vanced/comments/o3x5l2/question_is_it_me_or_you_all_have_the_same_issue/?utm_medium=android_app&utm_source=share

https://support.google.com/youtube/thread/77038657/cannot-fast-forward-by-video-progress-line?hl=en


Also when it was first removed by YT, people in Vanced subreddit repeatedly asked to have it back and where confused why it didn't work.

**Comment by PickleNik** [comment]
> > Tap to seek is just double tap on a side and it goes, right?
> 
> **Single tap** anywhere on the progressbar. This was the default behavior in stock YT for Android, until stupid Google decided to make it consistent with the iOS YT app and turned it into a "Tap, drag to seek" torture. Vanced brought this feature back as a toggle because several users asked for it.
> 
> (It's not like Android users are the majority and iOS should be consistent with Android if anything at all...)
> 
> The feature can be found in Vanced. Following screenshots show Vanced set to German language:
> 
> ![Screenshot_20220317-140700623 (1).png](https://user-images.githubusercontent.com/73917917/158815040-14069c5d-028c-4a95-9346-e8350c217f36.png)
> 
> ![Screenshot_20220317-140642243 (1).png](https://user-images.githubusercontent.com/73917917/158815062-cb3f7308-dde2-459e-b19a-c9cc350e0168.png)
> 
> There are tons of posts in the Google support forum about users being extremely upset that this important feature got downgraded into a "tap, drag/slide to seek".
> 
> Just to name a few: 
> 
> https://www.reddit.com/r/Vanced/comments/o3x5l2/question_is_it_me_or_you_all_have_the_same_issue/?utm_medium=android_app&utm_source=share
> 
> https://support.google.com/youtube/thread/77038657/cannot-fast-forward-by-video-progress-line?hl=en
> 
> 
> Also when it was first removed by YT, people in Vanced and YouTube subreddit repeatedly asked to have it back and where confused why it didn't work.
> 
> 

I believe that's the default behavior currently
