### ISSUE TITLE
Disable suggested videos popup after video ends

### ISSUE THREAD

**Issue by bagajohny** [VueTubeApp/VueTube#90]
I want to request feature to disable the popup of suggested videos right after a video ends on youtube app. Its very frustrating because i accidentally click on the video when all i wanted to do was minimize the player. 
[here is the screenshot of that.](https://i.imgur.com/whDHtYh.png)

I hope you get what i mean to say.

**Comment by PickleNik** [comment]
It's not enabled in the player by default currently and not planned to be in a blocking way, will probably be invoked via ![Screenshot_20220728-000113.png](https://user-images.githubusercontent.com/31113245/181417566-29d19be8-afd9-4d34-8134-f45aa1efe331.png)
this button instead of a popup.
In any case, #233 should satisfy any other needs.
